[2024-07-09T17:56:21.444+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pesquisa_industrial_anual_empresas.workspace manual__2024-07-09T17:56:19.665718+00:00 [queued]>
[2024-07-09T17:56:21.455+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pesquisa_industrial_anual_empresas.workspace manual__2024-07-09T17:56:19.665718+00:00 [queued]>
[2024-07-09T17:56:21.455+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-07-09T17:56:21.471+0000] {taskinstance.py:2217} INFO - Executing <Task(PapermillOperator): workspace> on 2024-07-09 17:56:19.665718+00:00
[2024-07-09T17:56:21.477+0000] {standard_task_runner.py:60} INFO - Started process 5324 to run task
[2024-07-09T17:56:21.480+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'pesquisa_industrial_anual_empresas', 'workspace', 'manual__2024-07-09T17:56:19.665718+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/pesquisa_industrial_anual_empresas/dags.py', '--cfg-path', '/tmp/tmp4wb7rnkl']
[2024-07-09T17:56:21.483+0000] {standard_task_runner.py:88} INFO - Job 23: Subtask workspace
[2024-07-09T17:56:21.536+0000] {task_command.py:423} INFO - Running <TaskInstance: pesquisa_industrial_anual_empresas.workspace manual__2024-07-09T17:56:19.665718+00:00 [running]> on host 049690d4da25
[2024-07-09T17:56:21.622+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='observatorio@sistemafiea.com.br' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pesquisa_industrial_anual_empresas' AIRFLOW_CTX_TASK_ID='workspace' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T17:56:19.665718+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-09T17:56:19.665718+00:00'
[2024-07-09T17:56:21.624+0000] {execute.py:83} INFO - Input Notebook:  /opt/***/dags/pesquisa_industrial_anual_empresas/notebooks/workspace.ipynb
[2024-07-09T17:56:21.625+0000] {execute.py:84} INFO - Output Notebook: /opt/***/dags/resultado/pesquisa_industrial_anual_empresas_workspace_2024-07-09.ipynb
[2024-07-09T17:56:23.094+0000] {clientwrap.py:44} INFO - Executing notebook with kernel: python3
[2024-07-09T17:56:29.608+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/papermill/operators/papermill.py", line 118, in execute
    pm.execute_notebook(
  File "/home/airflow/.local/lib/python3.11/site-packages/papermill/execute.py", line 131, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/home/airflow/.local/lib/python3.11/site-packages/papermill/execute.py", line 251, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [4]":
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[4], line 11
      4 response = requests.get(url)
      5 data = response.json()
      7 schema = StructType([
      8     StructField("id", StringType(), True),
      9     StructField("variavel", StringType(), True),
     10     StructField("unidade", StringType(), True),
---> 11     StructField("resultados", ArrayType(
     12         StructType([
     13             StructField("classificacoes", ArrayType(
     14                 StructType([
     15                     StructField("id", StringType(), True),
     16                     StructField("nome", StringType(), True),
     17                     StructField("categoria", MapType(StringType(), StringType()), True)
     18                 ])
     19             ), True),
     20             StructField("series", ArrayType(
     21                 StructType([
     22                     StructField("localidade", StructType([
     23                         StructField("id", StringType(), True),
     24                         StructField("nivel", StructType([
     25                             StructField("id", StringType(), True),
     26                             StructField("nome", StringType(), True)
     27                         ]), True),
     28                         StructField("nome", StringType(), True)
     29                     ]), True),
     30                     StructField("serie", MapType(StringType(), StringType()), True)
     31                 ])
     32             ), True)
     33         ])
     34     ), True)
     35 ])
     37 # Converta a lista de dicionários para um DataFrame usando o schema explícito
     38 rdd = spark.sparkContext.parallelize([data])

NameError: name 'ArrayType' is not defined

[2024-07-09T17:56:29.621+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=pesquisa_industrial_anual_empresas, task_id=workspace, execution_date=20240709T175619, start_date=20240709T175621, end_date=20240709T175629
[2024-07-09T17:56:29.638+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 23 for task workspace (
---------------------------------------------------------------------------
Exception encountered at "In [4]":
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[4], line 11
      4 response = requests.get(url)
      5 data = response.json()
      7 schema = StructType([
      8     StructField("id", StringType(), True),
      9     StructField("variavel", StringType(), True),
     10     StructField("unidade", StringType(), True),
---> 11     StructField("resultados", ArrayType(
     12         StructType([
     13             StructField("classificacoes", ArrayType(
     14                 StructType([
     15                     StructField("id", StringType(), True),
     16                     StructField("nome", StringType(), True),
     17                     StructField("categoria", MapType(StringType(), StringType()), True)
     18                 ])
     19             ), True),
     20             StructField("series", ArrayType(
     21                 StructType([
     22                     StructField("localidade", StructType([
     23                         StructField("id", StringType(), True),
     24                         StructField("nivel", StructType([
     25                             StructField("id", StringType(), True),
     26                             StructField("nome", StringType(), True)
     27                         ]), True),
     28                         StructField("nome", StringType(), True)
     29                     ]), True),
     30                     StructField("serie", MapType(StringType(), StringType()), True)
     31                 ])
     32             ), True)
     33         ])
     34     ), True)
     35 ])
     37 # Converta a lista de dicionários para um DataFrame usando o schema explícito
     38 rdd = spark.sparkContext.parallelize([data])

NameError: name 'ArrayType' is not defined
; 5324)
[2024-07-09T17:56:29.661+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-09T17:56:29.681+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
